import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "../components/_layout/header";
import { Footer } from "../components/_layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} bg-slate-950`}>
        <main className="grid grid-rows-10">
          <div className="row-span-1">
            <Header />
          </div>
          <div className="row-span-8">{children}</div>
          <div className="row-span-1">
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
